version: '3'

networks:
  app-tier:
    driver: bridge

volumes:
  minio-volume:
  redis-volume:

services:

  api:
    build: ./
    ports:
      - "5000:5000"
    environment:
      - MINIO_SERVER_ACCESS_KEY=minio-root-user
      - MINIO_SERVER_SECRET_KEY=minio-root-password
    networks:
      - app-tier
    depends_on:
      - minio
      - redis
    healthcheck:
      test: ["CMD", "python3", "/app/healthcheck.py"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  minio:
    image: 'bitnami/minio:2024.7.4'
    ports:
      - '9000:9000'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    networks:
      - app-tier
    volumes:
      - minio-volume:/bitnami/minio/data

  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    environment:
      REDIS_SAVE: "10 1"
    networks:
      - app-tier
    volumes:
      - redis-volume:/data